public with sharing class CL1 {

    String XYZ = 'How are you?';
    integer X = 50;
    integer Y = 90;
    integer result;
    
    Public string getMethod1()
    
    {
    
    Return XYZ;
    }
    
    Public Integer getadd()
    {
    
    result = X+Y;
    Return result;
    
    }
    
    Public integer getmultiple()
    {
    
    result= X*Y;
    return result;
    
    }
    
     
     
}